### ISSUE TITLE
UI Issues while editing Metadata in the Preview Page 

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#1091]
**Describe the bug**
When user is in the preview page of the document and opened information panel to edit the metadata. We have observed the below two issues

1. When user modifies any property and saves it refreshes the preview page
2. When user is in one of the text boxes and moves the cursor to go to specific text, instead of cursor moving in text box, it actually redirects to the next document
**Environment**
- ACA version: [e.g. 1.6] 1.7
- ACS version: [e.g. 6.1] 5.2

**To Reproduce**
1. Go to a word document preview
2. Click on "i" icon to open information panel.
3. Click edit and modify any metadata property and observe the preview page refresh
4. Edit the title property and move the cursor within text box and observe it loads next document preview

**Expected behavior**
It should not refresh the preview page for every metadata property refresh
It should not load the next document preview while moving cursor in text box.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by john-knowles** [comment]
Thank you for raising this issue.  I only seem to see this happening on Office files, so have logged https://issues.alfresco.com/jira/browse/ACA-2368 into the backlog.

**Comment by fcorti** [comment]
It should be fixed.
Can you please check again and close it eventually?

**Comment by adinapitul** [comment]
Still not completely fixed. 
- pressing Enter after editing a property is causing a reload of the doc
- pressing left / right keyboard arrows does NOT navigate to prev / next document anymore, but it does navigate to next / previous page of the document when the doc has multiple pages.

**Comment by DenysVuika** [comment]
closing as the corresponding Jira ticket is done
